# Generated by Django 6.0.2 on 2026-03-22 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.course'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.CharField(blank=True, help_text='e.g., BCA11, A, CS-3A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='e.g., 1, 2, 3', null=True),
        ),
    ]
