# Generated by Django 6.0.2 on 2026-03-22 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('exams', '0002_questionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='target_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_exams', to='academics.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='target_section',
            field=models.CharField(blank=True, help_text='Leave blank for all sections', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='target_year',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for all years', null=True),
        ),
    ]
